# Generated by Django 3.1.4 on 2020-12-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0002_auto_20201211_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
