# Generated by Django 3.1.4 on 2020-12-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workerapp', '0003_auto_20201211_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='title',
        ),
        migrations.AlterField(
            model_name='worksession',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
